#ifndef GLOBAL_H
# define GLOBAL_H

# define NICK_MAXSIZE 9
# define TIME_WAIT_SELECT_US 1000000
# define MAX_CMD_SIZE 512
# define IN_CIRCULAR_BUFF 64
# define OUT_CIRCULAR_BUFF	256
# define MAX_SIZE_CMD_STR	64

#endif
